name: tangram-test
ui: mocha-bdd
scripts:
  - node_modules/topojson/topojson.js
  - node_modules/es6ify/node_modules/traceur/bin/traceur-runtime.js
  - demos/lib/leaflet/leaflet.js
  - https://cdnjs.cloudflare.com/ajax/libs/sinon.js/1.7.3/sinon.js
  - https://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js

browsers:

  - name: firefox
    version: latest
    platform: "Windows 2012"
    firefox_profile:
      webgl.force-enabled: true
      webgl.disabled: false

browserify:
  - transform: es6ify