version: 2.0
jobs:
  build:
    docker:
      - image: cimg/node:22.12.0-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: tests
          command: npm run test
